### PR TITLE
S3 url support from jhonsfran and updated deps so tests pass

### PR DESCRIPTION
**Pull request by focusaurus**

### CODE REVIEW

**Comment by focusaurus** [comment]
Now failing eslint in a weird way. Investigating locally.

**Comment by jhonsfran1165** [comment]
Hi @focusaurus do you know how the package of this repo can be updated?

**Comment by focusaurus** [comment]
I think we need to manually publish these to npm as we don't have semantic release automation for this repo. It's on our queue to get to though.

**Comment by jhonsfran1165** [comment]
Got it so it's just a matter of time. Thanks!

**Comment by focusaurus** [comment]
OK I think I was able to publish the new versions to npm.

**Pull request merged**
