### PR TITLE
fix: remove package-lock.json file

### PR DESCRIPTION
**Pull request by focusaurus**
Lockfiles should not be used in libraries,
only applications

### CODE REVIEW

**Comment by focusaurus** [comment]
It's not viable for libraries to pin their dependency versions. It creates accretion meaning whenever there's any security updates in the entire dependency graph, we have to cut a new release of this library, which means we would basically need to automate that and do it near-daily. OR we just unpin the deps and let npm do the right thing. A deeply nested dep has a vuln, they publish a patch release, we do nothing, and the end users can update and get the fix.

**Comment by mikemurray** [comment]
@focusaurus @rosshadden  `package-lock.json` files are not published to npm. I just checked this package locally in Reaction, and there is no `package-lock.json` file in that folder.

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. 
- https://docs.npmjs.com/files/package-lock.json

This should mean that this lockfile is really only used when trying to run/test this repo in CI/locally. Everything else should update automatically assuming we use the `~` for version numbers.

**Comment by focusaurus** [comment]
Ah, that's an interesting point. Let me go double check on storefront and see the details of the nested dep that was causing issues. Maybe we just need to update our direct deps to latest.

**Comment by focusaurus** [comment]
Closing after having been schooled on the fact that npm/yarn ignore lock files except for the top-level one.

**Pull request closed without merging**
