### PR TITLE
Import bugs

### PR DESCRIPTION
**Pull request by focusaurus**
@jhonsfran Tests were failing for me locally due to a dep issue so I fixed that then cherry-picked your fix commit into this PR. If this all passes CI I'll merge and semantic release should publish new packages to npm.

### CODE REVIEW

**Comment by jhonsfran1165** [comment]
@focusaurus thank you! 🙌🙌

**Comment by jhonsfran1165** [comment]
@focusaurus is the package published automatically?

**Comment by focusaurus** [comment]
@jhonsfran1165 this package is not auto-published to npm but I manually published these latest releases.

**Comment by jhonsfran1165** [comment]
I got it thanks!

**Pull request merged**
