### PR TITLE
fix(file-collection): patch hoek and tunnel agent

### PR DESCRIPTION
**Pull request by spencern**
## Summary
This commit patches two vulnerable libs with snyk
1. hoek version 2.16.3
2. tunnel-agent version 0.4.3

These patches are added to the .snyk file
It adds a `snyk protect` command that is run during the `prepare` step
to ensure that the patches are applied

## Questions
I'm not certain how these patches will play with the build process. The `snyk protect` command added to the prepare step should run before `npm run build` is completed, but this may not work and it may be better to move these patches to the `reaction` repo and ignore the vulns here until we can update to a good version.

### CODE REVIEW

**Comment by aldeed** [comment]
@spencern I'm not 100% sure, but I believe running the `snyk protect` won't hurt but also won't do anything to the built package. The dependencies are installed in whatever app uses this package, so that app (e.g., Reaction) would have to have the `snyk protect` script. May or may not be worth keeping in this repo, too, to keep Snyk checks happy.

**Comment by spencern** [comment]
@aldeed yeah, we definitely will have to add it to Reaction as well for it to do much good. To keep snyk happy it's either this or adding ignores for them. 
It appears that `snyk protect` failed CI on the first attempt and then was skipped on the 2nd one.
I'm not convinced that this will be useful in the long run on Packages and I've added an Issue in `tus-node-server` https://github.com/tus/tus-node-server/issues/119#issuecomment-405690025 and will be submitting a PR to update it today which will make this irrelevant. I'm leaning towards closing and not merging this patch, but let's discuss it in our architecture meeting before making the final decision.

**Comment by spencern** [comment]
My PR to `tus-node-server` was merged, this issue should be resolved in their next release.

**Comment by spencern** [comment]
Closing this as we've decided not to patch.

**Pull request closed without merging**
